/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ArchitectRouteImport } from './routes/architect'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIdRouteImport } from './routes/services.$id'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectRoute = ArchitectRouteImport.update({
  id: '/architect',
  path: '/architect',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIdRoute = ServicesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ServicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/architect': typeof ArchitectRoute
  '/services': typeof ServicesRouteWithChildren
  '/services/$id': typeof ServicesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/architect': typeof ArchitectRoute
  '/services': typeof ServicesRouteWithChildren
  '/services/$id': typeof ServicesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/architect': typeof ArchitectRoute
  '/services': typeof ServicesRouteWithChildren
  '/services/$id': typeof ServicesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/architect' | '/services' | '/services/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/architect' | '/services' | '/services/$id'
  id: '__root__' | '/' | '/architect' | '/services' | '/services/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchitectRoute: typeof ArchitectRoute
  ServicesRoute: typeof ServicesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architect': {
      id: '/architect'
      path: '/architect'
      fullPath: '/architect'
      preLoaderRoute: typeof ArchitectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$id': {
      id: '/services/$id'
      path: '/$id'
      fullPath: '/services/$id'
      preLoaderRoute: typeof ServicesIdRouteImport
      parentRoute: typeof ServicesRoute
    }
  }
}

interface ServicesRouteChildren {
  ServicesIdRoute: typeof ServicesIdRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesIdRoute: ServicesIdRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchitectRoute: ArchitectRoute,
  ServicesRoute: ServicesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
